theme = "everforest_dark"

[editor.cursor-shape]
insert = "underline"

[editor.indent-guides]
render = true
character = "¦"

[editor]
rulers = [120]

[editor.lsp]
display-inlay-hints = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
