# theme = "everforest_dark"
theme = "gruvbox"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "¦"

[editor]
rulers = [120]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
# C-g = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- lazygit"
