[[language]]
name = "rust"
language-server = { command = "rust-analyzer" }

[language.config]
checkOnSave.command = "clippy"
checkOnSave.allFeatures = true
cargo = { loadOutDirsFromCheck = true, features = "all" }
procMacro.enable = true
diagnostics = { disabled = [ "unresolved-proc-macro" ] }

[language.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "/home/pdudko/.vscode/extensions/vadimcn.vscode-lldb-1.8.1/bin/lldb-server"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

