[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"
checkOnSave.allFeatures = true
cargo = { loadOutDirsFromCheck = true, features = "all" }
procMacro.enable = true
diagnostics = { disabled = [ "unresolved-proc-macro" ] }

[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]

