[[language]]
name = "rust"
language-server = { command = "rust-analyzer" }

[language.config]
checkOnSave.command = "clippy"
checkOnSave.allFeatures = true
cargo = { loadOutDirsFromCheck = true, features = "all" }
procMacro.enable = true
diagnostics = { disabled = [ "unresolved-proc-macro" ] }

[language.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

