[[language]]
name = "rust"
language-server = { command = "rust-analyzer" }

[language.config]
checkOnsave.command = "clippy"
checkOnSave.allFeatures = true
cargo = { loadOutDirsFromCheck = true }
procMacro.enable = true
diagnostics = { disabled = [ "unresolved-proc-macro" ] }
